### ISSUE TITLE
resolve hakiri security warnings

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/apps-gov-v2#86]
https://hakiri.io/github/presidential-innovation-fellows/apps-gov-v2/master/3eac2f18fc2e3816b830c60fda0eed2b373d5383

I believe these will be resolved with the brakeman updates

**Comment by lukad03** [comment]
Duplicate of https://github.com/presidential-innovation-fellows/apps-gov-v2/issues/85
