### ISSUE TITLE
update gems for ATO

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/apps-gov-v2#87]
https://gemnasium.com/github.com/presidential-innovation-fellows/apps-gov-v2

**Comment by lukad03** [comment]
@stroupaloop Can't update most of these b/c Draftsman is not Rails 5 compatible.

**Comment by stroupaloop** [comment]
Ok, I think the biggest issue is the upgrade from rails 4.2.5 to 4.2.7.1 and any subsequent gems, I upgraded to 4.2.7.1 in the `ato-compliance` branch, will merge it in and see what the report returns.

**Comment by stroupaloop** [comment]
Are all the gems out of date due to Rails 5 or can some be updated @lukad03 ?

I've merged in the upgrade from Rails 4.2.5 to 4.2.7.1 which resolved the critical issue.

Adding the upgrade to Rails 5 to the POAM, which will require an update from Draftsman as well.

**Comment by lukad03** [comment]
Closed b/c of the recent upgrade to Rails 5 - https://github.com/presidential-innovation-fellows/apps-gov-v2/commit/349be6d6250bacb77e9ccb329dacbb6dcb194c66
